// flow-typed signature: 3b3dc2cd2201ebc5960085eeeee72dd1
// flow-typed version: <<STUB>>/@iarna/toml_v^2.2.5/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@iarna/toml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@iarna/toml' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@iarna/toml/lib/create-date' {
  declare module.exports: any;
}

declare module '@iarna/toml/lib/create-datetime-float' {
  declare module.exports: any;
}

declare module '@iarna/toml/lib/create-datetime' {
  declare module.exports: any;
}

declare module '@iarna/toml/lib/create-time' {
  declare module.exports: any;
}

declare module '@iarna/toml/lib/format-num' {
  declare module.exports: any;
}

declare module '@iarna/toml/lib/parser-debug' {
  declare module.exports: any;
}

declare module '@iarna/toml/lib/parser' {
  declare module.exports: any;
}

declare module '@iarna/toml/lib/toml-parser' {
  declare module.exports: any;
}

declare module '@iarna/toml/parse-async' {
  declare module.exports: any;
}

declare module '@iarna/toml/parse-pretty-error' {
  declare module.exports: any;
}

declare module '@iarna/toml/parse-stream' {
  declare module.exports: any;
}

declare module '@iarna/toml/parse-string' {
  declare module.exports: any;
}

declare module '@iarna/toml/parse' {
  declare module.exports: any;
}

declare module '@iarna/toml/stringify' {
  declare module.exports: any;
}

declare module '@iarna/toml/toml' {
  declare module.exports: any;
}

// Filename aliases
declare module '@iarna/toml/lib/create-date.js' {
  declare module.exports: $Exports<'@iarna/toml/lib/create-date'>;
}
declare module '@iarna/toml/lib/create-datetime-float.js' {
  declare module.exports: $Exports<'@iarna/toml/lib/create-datetime-float'>;
}
declare module '@iarna/toml/lib/create-datetime.js' {
  declare module.exports: $Exports<'@iarna/toml/lib/create-datetime'>;
}
declare module '@iarna/toml/lib/create-time.js' {
  declare module.exports: $Exports<'@iarna/toml/lib/create-time'>;
}
declare module '@iarna/toml/lib/format-num.js' {
  declare module.exports: $Exports<'@iarna/toml/lib/format-num'>;
}
declare module '@iarna/toml/lib/parser-debug.js' {
  declare module.exports: $Exports<'@iarna/toml/lib/parser-debug'>;
}
declare module '@iarna/toml/lib/parser.js' {
  declare module.exports: $Exports<'@iarna/toml/lib/parser'>;
}
declare module '@iarna/toml/lib/toml-parser.js' {
  declare module.exports: $Exports<'@iarna/toml/lib/toml-parser'>;
}
declare module '@iarna/toml/parse-async.js' {
  declare module.exports: $Exports<'@iarna/toml/parse-async'>;
}
declare module '@iarna/toml/parse-pretty-error.js' {
  declare module.exports: $Exports<'@iarna/toml/parse-pretty-error'>;
}
declare module '@iarna/toml/parse-stream.js' {
  declare module.exports: $Exports<'@iarna/toml/parse-stream'>;
}
declare module '@iarna/toml/parse-string.js' {
  declare module.exports: $Exports<'@iarna/toml/parse-string'>;
}
declare module '@iarna/toml/parse.js' {
  declare module.exports: $Exports<'@iarna/toml/parse'>;
}
declare module '@iarna/toml/stringify.js' {
  declare module.exports: $Exports<'@iarna/toml/stringify'>;
}
declare module '@iarna/toml/toml.js' {
  declare module.exports: $Exports<'@iarna/toml/toml'>;
}
