// flow-typed signature: 3b3dc2cd2201ebc5960085eeeee72dd1
// flow-typed version: <<STUB>>/@iarna/toml_v^2.2.5/flow_v0.128.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@iarna/toml'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@iarna/toml' {
  declare module.exports: {
    stringify: <A>(object: A) => string,
    parse: <A>(tomlString: string | Buffer) => A,
  };
}
